domain_path: C:\Users\andre\OneDrive\Documents\GitHub\Zynq_Tutorial\vitis\platform\export\platform\sw\theName
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
