# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Zynq_Example/Zynq_Example.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Example || ORIG_REF_NAME==Zynq_Example} -quiet] -quiet

# IP: bd/Zynq_Example/ip/Zynq_Example_processing_system7_0_0/Zynq_Example_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Example_processing_system7_0_0 || ORIG_REF_NAME==Zynq_Example_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_Example/ip/Zynq_Example_proc_sys_reset_0_0/Zynq_Example_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Example_proc_sys_reset_0_0 || ORIG_REF_NAME==Zynq_Example_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Zynq_Example/ip/Zynq_Example_xbar_0/Zynq_Example_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Example_xbar_0 || ORIG_REF_NAME==Zynq_Example_xbar_0} -quiet] -quiet

# IP: bd/Zynq_Example/ip/Zynq_Example_auto_pc_1/Zynq_Example_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Example_auto_pc_1 || ORIG_REF_NAME==Zynq_Example_auto_pc_1} -quiet] -quiet

# IP: bd/Zynq_Example/ip/Zynq_Example_auto_pc_0/Zynq_Example_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Example_auto_pc_0 || ORIG_REF_NAME==Zynq_Example_auto_pc_0} -quiet] -quiet

# IP: bd/Zynq_Example/ip/Zynq_Example_axi_interconnect_0_0/Zynq_Example_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Example_axi_interconnect_0_0 || ORIG_REF_NAME==Zynq_Example_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Zynq_Example/ip/Zynq_Example_axi_gpio_0_0/Zynq_Example_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Example_axi_gpio_0_0 || ORIG_REF_NAME==Zynq_Example_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Zynq_Example/ip/Zynq_Example_axi_bram_ctrl_0_0/Zynq_Example_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Example_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Zynq_Example_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Zynq_Example/ip/Zynq_Example_blk_mem_gen_0_0/Zynq_Example_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Example_blk_mem_gen_0_0 || ORIG_REF_NAME==Zynq_Example_blk_mem_gen_0_0} -quiet] -quiet

# XDC: c:/Users/andre/OneDrive/Documents/GitHub/Zynq_Tutorial/Zynq_Tutorial.gen/sources_1/bd/Zynq_Example/Zynq_Example_ooc.xdc
